// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feedlightpb/feedlight.proto

/*
	Package feedlightpb is a generated protocol buffer package.

	It is generated from these files:
		feedlightpb/feedlight.proto

	It has these top-level messages:
		Feedback
		SimilarFeedbackRequest
		SimilarFeedbackResponse
		SubmitFeedbackRequest
		SubmitFeedbackResponse
		FeedbackRequest
		FeedbackResponse
		Status
*/
package feedlightpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Feedback struct {
	Feedback      string `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Score         int32  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Similar       bool   `protobuf:"varint,3,opt,name=similar,proto3" json:"similar,omitempty"`
	Dissimilar    bool   `protobuf:"varint,4,opt,name=dissimilar,proto3" json:"dissimilar,omitempty"`
	Response      string `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	SharePublicly bool   `protobuf:"varint,6,opt,name=share_publicly,json=sharePublicly,proto3" json:"share_publicly,omitempty"`
	Id            int64  `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64  `protobuf:"varint,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Feedback) Reset()                    { *m = Feedback{} }
func (*Feedback) ProtoMessage()               {}
func (*Feedback) Descriptor() ([]byte, []int) { return fileDescriptorFeedlight, []int{0} }

func (m *Feedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

func (m *Feedback) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Feedback) GetSimilar() bool {
	if m != nil {
		return m.Similar
	}
	return false
}

func (m *Feedback) GetDissimilar() bool {
	if m != nil {
		return m.Dissimilar
	}
	return false
}

func (m *Feedback) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *Feedback) GetSharePublicly() bool {
	if m != nil {
		return m.SharePublicly
	}
	return false
}

func (m *Feedback) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Feedback) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Feedback) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type SimilarFeedbackRequest struct {
	Domain   string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Feedback Feedback `protobuf:"bytes,1,opt,name=feedback" json:"feedback"`
}

func (m *SimilarFeedbackRequest) Reset()                    { *m = SimilarFeedbackRequest{} }
func (*SimilarFeedbackRequest) ProtoMessage()               {}
func (*SimilarFeedbackRequest) Descriptor() ([]byte, []int) { return fileDescriptorFeedlight, []int{1} }

func (m *SimilarFeedbackRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SimilarFeedbackRequest) GetFeedback() Feedback {
	if m != nil {
		return m.Feedback
	}
	return Feedback{}
}

type SimilarFeedbackResponse struct {
	Feedback []Feedback `protobuf:"bytes,1,rep,name=feedback" json:"feedback"`
}

func (m *SimilarFeedbackResponse) Reset()                    { *m = SimilarFeedbackResponse{} }
func (*SimilarFeedbackResponse) ProtoMessage()               {}
func (*SimilarFeedbackResponse) Descriptor() ([]byte, []int) { return fileDescriptorFeedlight, []int{2} }

func (m *SimilarFeedbackResponse) GetFeedback() []Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type SubmitFeedbackRequest struct {
	Domain   string     `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Email    string     `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Feedback Feedback   `protobuf:"bytes,2,opt,name=feedback" json:"feedback"`
	Similar  []Feedback `protobuf:"bytes,3,rep,name=similar" json:"similar"`
}

func (m *SubmitFeedbackRequest) Reset()                    { *m = SubmitFeedbackRequest{} }
func (*SubmitFeedbackRequest) ProtoMessage()               {}
func (*SubmitFeedbackRequest) Descriptor() ([]byte, []int) { return fileDescriptorFeedlight, []int{3} }

func (m *SubmitFeedbackRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SubmitFeedbackRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SubmitFeedbackRequest) GetFeedback() Feedback {
	if m != nil {
		return m.Feedback
	}
	return Feedback{}
}

func (m *SubmitFeedbackRequest) GetSimilar() []Feedback {
	if m != nil {
		return m.Similar
	}
	return nil
}

type SubmitFeedbackResponse struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *SubmitFeedbackResponse) Reset()                    { *m = SubmitFeedbackResponse{} }
func (*SubmitFeedbackResponse) ProtoMessage()               {}
func (*SubmitFeedbackResponse) Descriptor() ([]byte, []int) { return fileDescriptorFeedlight, []int{4} }

func (m *SubmitFeedbackResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FeedbackRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *FeedbackRequest) Reset()                    { *m = FeedbackRequest{} }
func (*FeedbackRequest) ProtoMessage()               {}
func (*FeedbackRequest) Descriptor() ([]byte, []int) { return fileDescriptorFeedlight, []int{5} }

func (m *FeedbackRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FeedbackResponse struct {
	Feedback Feedback   `protobuf:"bytes,1,opt,name=feedback" json:"feedback"`
	Domain   string     `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Similar  []Feedback `protobuf:"bytes,3,rep,name=similar" json:"similar"`
}

func (m *FeedbackResponse) Reset()                    { *m = FeedbackResponse{} }
func (*FeedbackResponse) ProtoMessage()               {}
func (*FeedbackResponse) Descriptor() ([]byte, []int) { return fileDescriptorFeedlight, []int{6} }

func (m *FeedbackResponse) GetFeedback() Feedback {
	if m != nil {
		return m.Feedback
	}
	return Feedback{}
}

func (m *FeedbackResponse) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *FeedbackResponse) GetSimilar() []Feedback {
	if m != nil {
		return m.Similar
	}
	return nil
}

// Status is used for the GRPC errors sent to the UI.
type Status struct {
	// The status code, which should be an enum value of [google.rpc.Code][google.rpc.Code].
	Code int32 `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	// A developer-facing error message, which should be in English. Any
	// user-facing error message should be localized and sent in the
	// [google.rpc.Status.details][google.rpc.Status.details] field, or localized by the client.
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptorFeedlight, []int{7} }

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Feedback)(nil), "feedlightpb.Feedback")
	proto.RegisterType((*SimilarFeedbackRequest)(nil), "feedlightpb.SimilarFeedbackRequest")
	proto.RegisterType((*SimilarFeedbackResponse)(nil), "feedlightpb.SimilarFeedbackResponse")
	proto.RegisterType((*SubmitFeedbackRequest)(nil), "feedlightpb.SubmitFeedbackRequest")
	proto.RegisterType((*SubmitFeedbackResponse)(nil), "feedlightpb.SubmitFeedbackResponse")
	proto.RegisterType((*FeedbackRequest)(nil), "feedlightpb.FeedbackRequest")
	proto.RegisterType((*FeedbackResponse)(nil), "feedlightpb.FeedbackResponse")
	proto.RegisterType((*Status)(nil), "feedlightpb.Status")
}
func (this *Feedback) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Feedback)
	if !ok {
		that2, ok := that.(Feedback)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Feedback != that1.Feedback {
		return false
	}
	if this.Score != that1.Score {
		return false
	}
	if this.Similar != that1.Similar {
		return false
	}
	if this.Dissimilar != that1.Dissimilar {
		return false
	}
	if this.Response != that1.Response {
		return false
	}
	if this.SharePublicly != that1.SharePublicly {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	if this.CreatedAt != that1.CreatedAt {
		return false
	}
	if this.UpdatedAt != that1.UpdatedAt {
		return false
	}
	return true
}
func (this *SimilarFeedbackRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SimilarFeedbackRequest)
	if !ok {
		that2, ok := that.(SimilarFeedbackRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Domain != that1.Domain {
		return false
	}
	if !this.Feedback.Equal(&that1.Feedback) {
		return false
	}
	return true
}
func (this *SimilarFeedbackResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SimilarFeedbackResponse)
	if !ok {
		that2, ok := that.(SimilarFeedbackResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Feedback) != len(that1.Feedback) {
		return false
	}
	for i := range this.Feedback {
		if !this.Feedback[i].Equal(&that1.Feedback[i]) {
			return false
		}
	}
	return true
}
func (this *SubmitFeedbackRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitFeedbackRequest)
	if !ok {
		that2, ok := that.(SubmitFeedbackRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Domain != that1.Domain {
		return false
	}
	if this.Email != that1.Email {
		return false
	}
	if !this.Feedback.Equal(&that1.Feedback) {
		return false
	}
	if len(this.Similar) != len(that1.Similar) {
		return false
	}
	for i := range this.Similar {
		if !this.Similar[i].Equal(&that1.Similar[i]) {
			return false
		}
	}
	return true
}
func (this *SubmitFeedbackResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitFeedbackResponse)
	if !ok {
		that2, ok := that.(SubmitFeedbackResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *FeedbackRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeedbackRequest)
	if !ok {
		that2, ok := that.(FeedbackRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *FeedbackResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FeedbackResponse)
	if !ok {
		that2, ok := that.(FeedbackResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Feedback.Equal(&that1.Feedback) {
		return false
	}
	if this.Domain != that1.Domain {
		return false
	}
	if len(this.Similar) != len(that1.Similar) {
		return false
	}
	for i := range this.Similar {
		if !this.Similar[i].Equal(&that1.Similar[i]) {
			return false
		}
	}
	return true
}
func (this *Status) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Status)
	if !ok {
		that2, ok := that.(Status)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	return true
}
func (this *Feedback) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 13)
	s = append(s, "&feedlightpb.Feedback{")
	s = append(s, "Feedback: "+fmt.Sprintf("%#v", this.Feedback)+",\n")
	s = append(s, "Score: "+fmt.Sprintf("%#v", this.Score)+",\n")
	s = append(s, "Similar: "+fmt.Sprintf("%#v", this.Similar)+",\n")
	s = append(s, "Dissimilar: "+fmt.Sprintf("%#v", this.Dissimilar)+",\n")
	s = append(s, "Response: "+fmt.Sprintf("%#v", this.Response)+",\n")
	s = append(s, "SharePublicly: "+fmt.Sprintf("%#v", this.SharePublicly)+",\n")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "CreatedAt: "+fmt.Sprintf("%#v", this.CreatedAt)+",\n")
	s = append(s, "UpdatedAt: "+fmt.Sprintf("%#v", this.UpdatedAt)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SimilarFeedbackRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&feedlightpb.SimilarFeedbackRequest{")
	s = append(s, "Domain: "+fmt.Sprintf("%#v", this.Domain)+",\n")
	s = append(s, "Feedback: "+strings.Replace(this.Feedback.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SimilarFeedbackResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&feedlightpb.SimilarFeedbackResponse{")
	if this.Feedback != nil {
		vs := make([]*Feedback, len(this.Feedback))
		for i := range vs {
			vs[i] = &this.Feedback[i]
		}
		s = append(s, "Feedback: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SubmitFeedbackRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&feedlightpb.SubmitFeedbackRequest{")
	s = append(s, "Domain: "+fmt.Sprintf("%#v", this.Domain)+",\n")
	s = append(s, "Email: "+fmt.Sprintf("%#v", this.Email)+",\n")
	s = append(s, "Feedback: "+strings.Replace(this.Feedback.GoString(), `&`, ``, 1)+",\n")
	if this.Similar != nil {
		vs := make([]*Feedback, len(this.Similar))
		for i := range vs {
			vs[i] = &this.Similar[i]
		}
		s = append(s, "Similar: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SubmitFeedbackResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&feedlightpb.SubmitFeedbackResponse{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *FeedbackRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&feedlightpb.FeedbackRequest{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *FeedbackResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&feedlightpb.FeedbackResponse{")
	s = append(s, "Feedback: "+strings.Replace(this.Feedback.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "Domain: "+fmt.Sprintf("%#v", this.Domain)+",\n")
	if this.Similar != nil {
		vs := make([]*Feedback, len(this.Similar))
		for i := range vs {
			vs[i] = &this.Similar[i]
		}
		s = append(s, "Similar: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *Status) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&feedlightpb.Status{")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "Message: "+fmt.Sprintf("%#v", this.Message)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringFeedlight(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for FeedbackService service

type FeedbackServiceClient interface {
	SimilarFeedback(ctx context.Context, in *SimilarFeedbackRequest, opts ...grpc.CallOption) (*SimilarFeedbackResponse, error)
	SubmitFeedback(ctx context.Context, in *SubmitFeedbackRequest, opts ...grpc.CallOption) (*SubmitFeedbackResponse, error)
	Feedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error)
}

type feedbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedbackServiceClient(cc *grpc.ClientConn) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) SimilarFeedback(ctx context.Context, in *SimilarFeedbackRequest, opts ...grpc.CallOption) (*SimilarFeedbackResponse, error) {
	out := new(SimilarFeedbackResponse)
	err := grpc.Invoke(ctx, "/feedlightpb.FeedbackService/SimilarFeedback", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) SubmitFeedback(ctx context.Context, in *SubmitFeedbackRequest, opts ...grpc.CallOption) (*SubmitFeedbackResponse, error) {
	out := new(SubmitFeedbackResponse)
	err := grpc.Invoke(ctx, "/feedlightpb.FeedbackService/SubmitFeedback", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) Feedback(ctx context.Context, in *FeedbackRequest, opts ...grpc.CallOption) (*FeedbackResponse, error) {
	out := new(FeedbackResponse)
	err := grpc.Invoke(ctx, "/feedlightpb.FeedbackService/Feedback", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for FeedbackService service

type FeedbackServiceServer interface {
	SimilarFeedback(context.Context, *SimilarFeedbackRequest) (*SimilarFeedbackResponse, error)
	SubmitFeedback(context.Context, *SubmitFeedbackRequest) (*SubmitFeedbackResponse, error)
	Feedback(context.Context, *FeedbackRequest) (*FeedbackResponse, error)
}

func RegisterFeedbackServiceServer(s *grpc.Server, srv FeedbackServiceServer) {
	s.RegisterService(&_FeedbackService_serviceDesc, srv)
}

func _FeedbackService_SimilarFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).SimilarFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedlightpb.FeedbackService/SimilarFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).SimilarFeedback(ctx, req.(*SimilarFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_SubmitFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).SubmitFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedlightpb.FeedbackService/SubmitFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).SubmitFeedback(ctx, req.(*SubmitFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_Feedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).Feedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedlightpb.FeedbackService/Feedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).Feedback(ctx, req.(*FeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feedlightpb.FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimilarFeedback",
			Handler:    _FeedbackService_SimilarFeedback_Handler,
		},
		{
			MethodName: "SubmitFeedback",
			Handler:    _FeedbackService_SubmitFeedback_Handler,
		},
		{
			MethodName: "Feedback",
			Handler:    _FeedbackService_Feedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedlightpb/feedlight.proto",
}

func (m *Feedback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Feedback) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Feedback) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Feedback)))
		i += copy(dAtA[i:], m.Feedback)
	}
	if m.Score != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Score))
	}
	if m.Similar {
		dAtA[i] = 0x18
		i++
		if m.Similar {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Dissimilar {
		dAtA[i] = 0x20
		i++
		if m.Dissimilar {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Response) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Response)))
		i += copy(dAtA[i:], m.Response)
	}
	if m.SharePublicly {
		dAtA[i] = 0x30
		i++
		if m.SharePublicly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.CreatedAt != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.CreatedAt))
	}
	if m.Id != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Id))
	}
	if m.UpdatedAt != 0 {
		dAtA[i] = 0x48
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.UpdatedAt))
	}
	return i, nil
}

func (m *SimilarFeedbackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimilarFeedbackRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintFeedlight(dAtA, i, uint64(m.Feedback.Size()))
	n1, err := m.Feedback.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	if len(m.Domain) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Domain)))
		i += copy(dAtA[i:], m.Domain)
	}
	return i, nil
}

func (m *SimilarFeedbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimilarFeedbackResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Feedback) > 0 {
		for _, msg := range m.Feedback {
			dAtA[i] = 0xa
			i++
			i = encodeVarintFeedlight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *SubmitFeedbackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitFeedbackRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Email) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Email)))
		i += copy(dAtA[i:], m.Email)
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintFeedlight(dAtA, i, uint64(m.Feedback.Size()))
	n2, err := m.Feedback.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.Similar) > 0 {
		for _, msg := range m.Similar {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintFeedlight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Domain) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Domain)))
		i += copy(dAtA[i:], m.Domain)
	}
	return i, nil
}

func (m *SubmitFeedbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitFeedbackResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *FeedbackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedbackRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *FeedbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedbackResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintFeedlight(dAtA, i, uint64(m.Feedback.Size()))
	n3, err := m.Feedback.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if len(m.Domain) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Domain)))
		i += copy(dAtA[i:], m.Domain)
	}
	if len(m.Similar) > 0 {
		for _, msg := range m.Similar {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintFeedlight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Message)))
		i += copy(dAtA[i:], m.Message)
	}
	if m.Code != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Code))
	}
	return i, nil
}

func encodeVarintFeedlight(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Feedback) Size() (n int) {
	var l int
	_ = l
	l = len(m.Feedback)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	if m.Score != 0 {
		n += 1 + sovFeedlight(uint64(m.Score))
	}
	if m.Similar {
		n += 2
	}
	if m.Dissimilar {
		n += 2
	}
	l = len(m.Response)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	if m.SharePublicly {
		n += 2
	}
	if m.CreatedAt != 0 {
		n += 1 + sovFeedlight(uint64(m.CreatedAt))
	}
	if m.Id != 0 {
		n += 1 + sovFeedlight(uint64(m.Id))
	}
	if m.UpdatedAt != 0 {
		n += 1 + sovFeedlight(uint64(m.UpdatedAt))
	}
	return n
}

func (m *SimilarFeedbackRequest) Size() (n int) {
	var l int
	_ = l
	l = m.Feedback.Size()
	n += 1 + l + sovFeedlight(uint64(l))
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	return n
}

func (m *SimilarFeedbackResponse) Size() (n int) {
	var l int
	_ = l
	if len(m.Feedback) > 0 {
		for _, e := range m.Feedback {
			l = e.Size()
			n += 1 + l + sovFeedlight(uint64(l))
		}
	}
	return n
}

func (m *SubmitFeedbackRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	l = m.Feedback.Size()
	n += 1 + l + sovFeedlight(uint64(l))
	if len(m.Similar) > 0 {
		for _, e := range m.Similar {
			l = e.Size()
			n += 1 + l + sovFeedlight(uint64(l))
		}
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	return n
}

func (m *SubmitFeedbackResponse) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFeedlight(uint64(m.Id))
	}
	return n
}

func (m *FeedbackRequest) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFeedlight(uint64(m.Id))
	}
	return n
}

func (m *FeedbackResponse) Size() (n int) {
	var l int
	_ = l
	l = m.Feedback.Size()
	n += 1 + l + sovFeedlight(uint64(l))
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	if len(m.Similar) > 0 {
		for _, e := range m.Similar {
			l = e.Size()
			n += 1 + l + sovFeedlight(uint64(l))
		}
	}
	return n
}

func (m *Status) Size() (n int) {
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	if m.Code != 0 {
		n += 1 + sovFeedlight(uint64(m.Code))
	}
	return n
}

func sovFeedlight(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozFeedlight(x uint64) (n int) {
	return sovFeedlight(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Feedback) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Feedback{`,
		`Feedback:` + fmt.Sprintf("%v", this.Feedback) + `,`,
		`Score:` + fmt.Sprintf("%v", this.Score) + `,`,
		`Similar:` + fmt.Sprintf("%v", this.Similar) + `,`,
		`Dissimilar:` + fmt.Sprintf("%v", this.Dissimilar) + `,`,
		`Response:` + fmt.Sprintf("%v", this.Response) + `,`,
		`SharePublicly:` + fmt.Sprintf("%v", this.SharePublicly) + `,`,
		`CreatedAt:` + fmt.Sprintf("%v", this.CreatedAt) + `,`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`UpdatedAt:` + fmt.Sprintf("%v", this.UpdatedAt) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SimilarFeedbackRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SimilarFeedbackRequest{`,
		`Feedback:` + strings.Replace(strings.Replace(this.Feedback.String(), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`Domain:` + fmt.Sprintf("%v", this.Domain) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SimilarFeedbackResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SimilarFeedbackResponse{`,
		`Feedback:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Feedback), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SubmitFeedbackRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SubmitFeedbackRequest{`,
		`Email:` + fmt.Sprintf("%v", this.Email) + `,`,
		`Feedback:` + strings.Replace(strings.Replace(this.Feedback.String(), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`Similar:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Similar), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`Domain:` + fmt.Sprintf("%v", this.Domain) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SubmitFeedbackResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SubmitFeedbackResponse{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FeedbackRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FeedbackRequest{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func (this *FeedbackResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&FeedbackResponse{`,
		`Feedback:` + strings.Replace(strings.Replace(this.Feedback.String(), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`Domain:` + fmt.Sprintf("%v", this.Domain) + `,`,
		`Similar:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Similar), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *Status) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Status{`,
		`Message:` + fmt.Sprintf("%v", this.Message) + `,`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringFeedlight(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Feedback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Feedback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Feedback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feedback = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Similar", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Similar = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dissimilar", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Dissimilar = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Response = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SharePublicly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SharePublicly = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpdatedAt", wireType)
			}
			m.UpdatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UpdatedAt |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimilarFeedbackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimilarFeedbackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimilarFeedbackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Feedback.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimilarFeedbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimilarFeedbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimilarFeedbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feedback = append(m.Feedback, Feedback{})
			if err := m.Feedback[len(m.Feedback)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitFeedbackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitFeedbackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitFeedbackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Feedback.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Similar", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Similar = append(m.Similar, Feedback{})
			if err := m.Similar[len(m.Similar)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitFeedbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitFeedbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitFeedbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedbackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedbackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedbackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Feedback.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Similar", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Similar = append(m.Similar, Feedback{})
			if err := m.Similar[len(m.Similar)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Status) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Status: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Status: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeedlight(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthFeedlight
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowFeedlight
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipFeedlight(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthFeedlight = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeedlight   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("feedlightpb/feedlight.proto", fileDescriptorFeedlight) }

var fileDescriptorFeedlight = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcd, 0x6e, 0xd3, 0x4e,
	0x1c, 0xcc, 0x3a, 0x1f, 0x4d, 0xb6, 0xfa, 0xb7, 0x7f, 0xad, 0xda, 0x62, 0x85, 0x76, 0x09, 0x2e,
	0x85, 0x88, 0x96, 0x58, 0x0d, 0x02, 0x24, 0x6e, 0xed, 0x81, 0x33, 0x72, 0x1e, 0xa0, 0x5a, 0xdb,
	0x1b, 0x67, 0x85, 0x9d, 0x35, 0xf6, 0xba, 0x12, 0x37, 0xc4, 0x85, 0x0b, 0x87, 0x4a, 0xdc, 0x78,
	0x02, 0x78, 0x00, 0xde, 0xa1, 0xc7, 0x4a, 0x5c, 0x38, 0x21, 0x62, 0x38, 0x70, 0xec, 0x23, 0xa0,
	0xac, 0xed, 0xd4, 0x36, 0x49, 0xcb, 0xc7, 0x6d, 0xe7, 0xb7, 0x63, 0xcd, 0xec, 0xcc, 0x7a, 0xe1,
	0xf5, 0x21, 0xa5, 0xb6, 0xcb, 0x9c, 0x91, 0xf0, 0x4d, 0x7d, 0xb6, 0xee, 0xf9, 0x01, 0x17, 0x1c,
	0x2d, 0xe7, 0x36, 0xdb, 0x9b, 0x0e, 0xe7, 0x8e, 0x4b, 0x75, 0xe2, 0x33, 0x9d, 0x8c, 0xc7, 0x5c,
	0x10, 0xc1, 0xf8, 0x38, 0x4c, 0xa8, 0xed, 0x7b, 0x0e, 0x13, 0xa3, 0xc8, 0xec, 0x59, 0xdc, 0xd3,
	0x1d, 0xee, 0x70, 0x5d, 0x8e, 0xcd, 0x68, 0x28, 0x91, 0x04, 0x72, 0x95, 0xd0, 0xb5, 0xd7, 0x0a,
	0x6c, 0x3e, 0xa1, 0xd4, 0x36, 0x89, 0xf5, 0x0c, 0xb5, 0x61, 0x73, 0x98, 0xae, 0x55, 0xd0, 0x01,
	0xdd, 0x96, 0x31, 0xc3, 0x68, 0x0d, 0xd6, 0x43, 0x8b, 0x07, 0x54, 0x55, 0x3a, 0xa0, 0x5b, 0x37,
	0x12, 0x80, 0x54, 0xb8, 0x14, 0x32, 0x8f, 0xb9, 0x24, 0x50, 0xab, 0x1d, 0xd0, 0x6d, 0x1a, 0x19,
	0x44, 0x18, 0x42, 0x9b, 0x85, 0xd9, 0x66, 0x4d, 0x6e, 0xe6, 0x26, 0x53, 0xad, 0x80, 0x86, 0x3e,
	0x1f, 0x87, 0x54, 0xad, 0x27, 0x5a, 0x19, 0x46, 0x3b, 0x70, 0x25, 0x1c, 0x91, 0x80, 0x1e, 0xf9,
	0x91, 0xe9, 0x32, 0xcb, 0x7d, 0xa1, 0x36, 0xe4, 0xf7, 0xff, 0xc9, 0xe9, 0xd3, 0x74, 0x88, 0xb6,
	0x20, 0xb4, 0x02, 0x4a, 0x04, 0xb5, 0x8f, 0x88, 0x50, 0x97, 0x3a, 0xa0, 0x5b, 0x35, 0x5a, 0xe9,
	0xe4, 0x40, 0xa0, 0x15, 0xa8, 0x30, 0x5b, 0x6d, 0xca, 0xb1, 0xc2, 0xec, 0x29, 0x3d, 0xf2, 0xed,
	0x8c, 0xde, 0x4a, 0xe8, 0xe9, 0xe4, 0x40, 0x68, 0x0c, 0x6e, 0x0c, 0x12, 0x6f, 0x59, 0x1e, 0x06,
	0x7d, 0x1e, 0xd1, 0x50, 0xa0, 0x47, 0xa5, 0x58, 0x96, 0xfb, 0xeb, 0xbd, 0x5c, 0x21, 0xbd, 0x8c,
	0x7f, 0x58, 0x3b, 0xfd, 0x72, 0xa3, 0x92, 0xcb, 0x6c, 0x03, 0x36, 0x6c, 0xee, 0x11, 0x36, 0x96,
	0xa1, 0xb5, 0x8c, 0x14, 0x69, 0x06, 0xbc, 0xf6, 0x8b, 0x54, 0x7a, 0xf4, 0xa2, 0x56, 0xf5, 0xb7,
	0xb5, 0xb4, 0x8f, 0x00, 0xae, 0x0f, 0x22, 0xd3, 0x63, 0xa2, 0x6c, 0x7f, 0x0d, 0xd6, 0xa9, 0x47,
	0x98, 0x9b, 0x56, 0x9a, 0x80, 0x82, 0x90, 0xf2, 0x27, 0x87, 0x7a, 0x90, 0xaf, 0xfc, 0x4a, 0x83,
	0xb3, 0xfb, 0x70, 0x91, 0x45, 0xad, 0x90, 0x45, 0x17, 0x6e, 0x94, 0x6d, 0xa7, 0x51, 0x24, 0xfd,
	0x81, 0xac, 0x3f, 0xed, 0x26, 0x5c, 0x2d, 0x1f, 0xad, 0x4c, 0x79, 0x07, 0xe0, 0xff, 0x57, 0x44,
	0xfa, 0xef, 0xf5, 0xfd, 0x65, 0x02, 0xda, 0x43, 0xd8, 0x18, 0x08, 0x22, 0xa2, 0x70, 0xfa, 0xd7,
	0x78, 0x34, 0x0c, 0x89, 0x43, 0xd3, 0x4e, 0x32, 0x88, 0x10, 0xac, 0x59, 0xdc, 0xce, 0x7e, 0x32,
	0xb9, 0xee, 0x7f, 0xa8, 0x5e, 0x1c, 0x7c, 0x40, 0x83, 0x63, 0x66, 0x51, 0x74, 0x02, 0xe0, 0x6a,
	0xe9, 0x0a, 0xa1, 0xed, 0x82, 0x8b, 0xf9, 0x77, 0xb9, 0x7d, 0xeb, 0x72, 0x52, 0x12, 0x99, 0xd6,
	0x7f, 0xf5, 0xe9, 0xfb, 0x5b, 0x65, 0x4f, 0xbb, 0x23, 0x1f, 0x99, 0xe3, 0x7d, 0xbd, 0xa4, 0xaf,
	0x97, 0x3e, 0x7c, 0x0c, 0xee, 0xa2, 0x37, 0x00, 0xae, 0x14, 0x9b, 0x44, 0x5a, 0x51, 0x6c, 0xde,
	0xed, 0x6c, 0x6f, 0x5f, 0xca, 0x49, 0xfd, 0xec, 0x4b, 0x3f, 0xbb, 0xda, 0xed, 0x85, 0x7e, 0x0a,
	0xdf, 0x4d, 0xed, 0x88, 0xdc, 0xbb, 0xb6, 0x39, 0xb7, 0x9f, 0xcc, 0xc1, 0xd6, 0x82, 0xdd, 0x54,
	0x7b, 0x57, 0x6a, 0xef, 0x68, 0x9d, 0x45, 0xda, 0x39, 0xd5, 0xc3, 0xbd, 0xb3, 0x09, 0xae, 0x7c,
	0x9e, 0xe0, 0xca, 0xf9, 0x04, 0x83, 0x97, 0x31, 0x06, 0xef, 0x63, 0x0c, 0x4e, 0x63, 0x0c, 0xce,
	0x62, 0x0c, 0xbe, 0xc6, 0x18, 0xfc, 0x88, 0x71, 0xe5, 0x3c, 0xc6, 0xe0, 0xe4, 0x1b, 0xae, 0x98,
	0x0d, 0xf9, 0x06, 0xdf, 0xff, 0x19, 0x00, 0x00, 0xff, 0xff, 0x04, 0xec, 0x15, 0xc7, 0xfc, 0x05,
	0x00, 0x00,
}
