// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: feedlightpb/feedlight.proto

package feedlightpb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import strings "strings"
import reflect "reflect"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Feedback struct {
	Feedback             string   `protobuf:"bytes,1,opt,name=feedback,proto3" json:"feedback,omitempty"`
	Score                int32    `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Similar              bool     `protobuf:"varint,3,opt,name=similar,proto3" json:"similar,omitempty"`
	Dissimilar           bool     `protobuf:"varint,4,opt,name=dissimilar,proto3" json:"dissimilar,omitempty"`
	Response             string   `protobuf:"bytes,5,opt,name=response,proto3" json:"response,omitempty"`
	SharePublicly        bool     `protobuf:"varint,6,opt,name=share_publicly,json=sharePublicly,proto3" json:"share_publicly,omitempty"`
	Created              int64    `protobuf:"varint,7,opt,name=created,proto3" json:"created,omitempty"`
	Id                   int64    `protobuf:"varint,8,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feedback) Reset()      { *m = Feedback{} }
func (*Feedback) ProtoMessage() {}
func (*Feedback) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedlight_1b982d423c5632eb, []int{0}
}
func (m *Feedback) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Feedback) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Feedback.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *Feedback) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feedback.Merge(dst, src)
}
func (m *Feedback) XXX_Size() int {
	return m.Size()
}
func (m *Feedback) XXX_DiscardUnknown() {
	xxx_messageInfo_Feedback.DiscardUnknown(m)
}

var xxx_messageInfo_Feedback proto.InternalMessageInfo

func (m *Feedback) GetFeedback() string {
	if m != nil {
		return m.Feedback
	}
	return ""
}

func (m *Feedback) GetScore() int32 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *Feedback) GetSimilar() bool {
	if m != nil {
		return m.Similar
	}
	return false
}

func (m *Feedback) GetDissimilar() bool {
	if m != nil {
		return m.Dissimilar
	}
	return false
}

func (m *Feedback) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *Feedback) GetSharePublicly() bool {
	if m != nil {
		return m.SharePublicly
	}
	return false
}

func (m *Feedback) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Feedback) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type SimilarFeedbackRequest struct {
	Domain               string   `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Feedback             Feedback `protobuf:"bytes,1,opt,name=feedback" json:"feedback"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SimilarFeedbackRequest) Reset()      { *m = SimilarFeedbackRequest{} }
func (*SimilarFeedbackRequest) ProtoMessage() {}
func (*SimilarFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedlight_1b982d423c5632eb, []int{1}
}
func (m *SimilarFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimilarFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimilarFeedbackRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SimilarFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarFeedbackRequest.Merge(dst, src)
}
func (m *SimilarFeedbackRequest) XXX_Size() int {
	return m.Size()
}
func (m *SimilarFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarFeedbackRequest proto.InternalMessageInfo

func (m *SimilarFeedbackRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SimilarFeedbackRequest) GetFeedback() Feedback {
	if m != nil {
		return m.Feedback
	}
	return Feedback{}
}

type SimilarFeedbackResponse struct {
	Feedback             []Feedback `protobuf:"bytes,1,rep,name=feedback" json:"feedback"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SimilarFeedbackResponse) Reset()      { *m = SimilarFeedbackResponse{} }
func (*SimilarFeedbackResponse) ProtoMessage() {}
func (*SimilarFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedlight_1b982d423c5632eb, []int{2}
}
func (m *SimilarFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SimilarFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SimilarFeedbackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SimilarFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SimilarFeedbackResponse.Merge(dst, src)
}
func (m *SimilarFeedbackResponse) XXX_Size() int {
	return m.Size()
}
func (m *SimilarFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SimilarFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SimilarFeedbackResponse proto.InternalMessageInfo

func (m *SimilarFeedbackResponse) GetFeedback() []Feedback {
	if m != nil {
		return m.Feedback
	}
	return nil
}

type SubmitFeedbackRequest struct {
	Domain               string     `protobuf:"bytes,4,opt,name=domain,proto3" json:"domain,omitempty"`
	Email                string     `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Feedback             Feedback   `protobuf:"bytes,2,opt,name=feedback" json:"feedback"`
	Similar              []Feedback `protobuf:"bytes,3,rep,name=similar" json:"similar"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SubmitFeedbackRequest) Reset()      { *m = SubmitFeedbackRequest{} }
func (*SubmitFeedbackRequest) ProtoMessage() {}
func (*SubmitFeedbackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedlight_1b982d423c5632eb, []int{3}
}
func (m *SubmitFeedbackRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitFeedbackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitFeedbackRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SubmitFeedbackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitFeedbackRequest.Merge(dst, src)
}
func (m *SubmitFeedbackRequest) XXX_Size() int {
	return m.Size()
}
func (m *SubmitFeedbackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitFeedbackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitFeedbackRequest proto.InternalMessageInfo

func (m *SubmitFeedbackRequest) GetDomain() string {
	if m != nil {
		return m.Domain
	}
	return ""
}

func (m *SubmitFeedbackRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SubmitFeedbackRequest) GetFeedback() Feedback {
	if m != nil {
		return m.Feedback
	}
	return Feedback{}
}

func (m *SubmitFeedbackRequest) GetSimilar() []Feedback {
	if m != nil {
		return m.Similar
	}
	return nil
}

type SubmitFeedbackResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SubmitFeedbackResponse) Reset()      { *m = SubmitFeedbackResponse{} }
func (*SubmitFeedbackResponse) ProtoMessage() {}
func (*SubmitFeedbackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_feedlight_1b982d423c5632eb, []int{4}
}
func (m *SubmitFeedbackResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubmitFeedbackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubmitFeedbackResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *SubmitFeedbackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubmitFeedbackResponse.Merge(dst, src)
}
func (m *SubmitFeedbackResponse) XXX_Size() int {
	return m.Size()
}
func (m *SubmitFeedbackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SubmitFeedbackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SubmitFeedbackResponse proto.InternalMessageInfo

func (m *SubmitFeedbackResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Feedback)(nil), "feedlightpb.Feedback")
	proto.RegisterType((*SimilarFeedbackRequest)(nil), "feedlightpb.SimilarFeedbackRequest")
	proto.RegisterType((*SimilarFeedbackResponse)(nil), "feedlightpb.SimilarFeedbackResponse")
	proto.RegisterType((*SubmitFeedbackRequest)(nil), "feedlightpb.SubmitFeedbackRequest")
	proto.RegisterType((*SubmitFeedbackResponse)(nil), "feedlightpb.SubmitFeedbackResponse")
}
func (this *Feedback) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Feedback)
	if !ok {
		that2, ok := that.(Feedback)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Feedback != that1.Feedback {
		return false
	}
	if this.Score != that1.Score {
		return false
	}
	if this.Similar != that1.Similar {
		return false
	}
	if this.Dissimilar != that1.Dissimilar {
		return false
	}
	if this.Response != that1.Response {
		return false
	}
	if this.SharePublicly != that1.SharePublicly {
		return false
	}
	if this.Created != that1.Created {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *SimilarFeedbackRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SimilarFeedbackRequest)
	if !ok {
		that2, ok := that.(SimilarFeedbackRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Domain != that1.Domain {
		return false
	}
	if !this.Feedback.Equal(&that1.Feedback) {
		return false
	}
	return true
}
func (this *SimilarFeedbackResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SimilarFeedbackResponse)
	if !ok {
		that2, ok := that.(SimilarFeedbackResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Feedback) != len(that1.Feedback) {
		return false
	}
	for i := range this.Feedback {
		if !this.Feedback[i].Equal(&that1.Feedback[i]) {
			return false
		}
	}
	return true
}
func (this *SubmitFeedbackRequest) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitFeedbackRequest)
	if !ok {
		that2, ok := that.(SubmitFeedbackRequest)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Domain != that1.Domain {
		return false
	}
	if this.Email != that1.Email {
		return false
	}
	if !this.Feedback.Equal(&that1.Feedback) {
		return false
	}
	if len(this.Similar) != len(that1.Similar) {
		return false
	}
	for i := range this.Similar {
		if !this.Similar[i].Equal(&that1.Similar[i]) {
			return false
		}
	}
	return true
}
func (this *SubmitFeedbackResponse) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*SubmitFeedbackResponse)
	if !ok {
		that2, ok := that.(SubmitFeedbackResponse)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Id != that1.Id {
		return false
	}
	return true
}
func (this *Feedback) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 12)
	s = append(s, "&feedlightpb.Feedback{")
	s = append(s, "Feedback: "+fmt.Sprintf("%#v", this.Feedback)+",\n")
	s = append(s, "Score: "+fmt.Sprintf("%#v", this.Score)+",\n")
	s = append(s, "Similar: "+fmt.Sprintf("%#v", this.Similar)+",\n")
	s = append(s, "Dissimilar: "+fmt.Sprintf("%#v", this.Dissimilar)+",\n")
	s = append(s, "Response: "+fmt.Sprintf("%#v", this.Response)+",\n")
	s = append(s, "SharePublicly: "+fmt.Sprintf("%#v", this.SharePublicly)+",\n")
	s = append(s, "Created: "+fmt.Sprintf("%#v", this.Created)+",\n")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SimilarFeedbackRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&feedlightpb.SimilarFeedbackRequest{")
	s = append(s, "Domain: "+fmt.Sprintf("%#v", this.Domain)+",\n")
	s = append(s, "Feedback: "+strings.Replace(this.Feedback.GoString(), `&`, ``, 1)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SimilarFeedbackResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&feedlightpb.SimilarFeedbackResponse{")
	if this.Feedback != nil {
		vs := make([]*Feedback, len(this.Feedback))
		for i := range vs {
			vs[i] = &this.Feedback[i]
		}
		s = append(s, "Feedback: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SubmitFeedbackRequest) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 8)
	s = append(s, "&feedlightpb.SubmitFeedbackRequest{")
	s = append(s, "Domain: "+fmt.Sprintf("%#v", this.Domain)+",\n")
	s = append(s, "Email: "+fmt.Sprintf("%#v", this.Email)+",\n")
	s = append(s, "Feedback: "+strings.Replace(this.Feedback.GoString(), `&`, ``, 1)+",\n")
	if this.Similar != nil {
		vs := make([]*Feedback, len(this.Similar))
		for i := range vs {
			vs[i] = &this.Similar[i]
		}
		s = append(s, "Similar: "+fmt.Sprintf("%#v", vs)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SubmitFeedbackResponse) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&feedlightpb.SubmitFeedbackResponse{")
	s = append(s, "Id: "+fmt.Sprintf("%#v", this.Id)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringFeedlight(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FeedbackServiceClient is the client API for FeedbackService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FeedbackServiceClient interface {
	SimilarFeedback(ctx context.Context, in *SimilarFeedbackRequest, opts ...grpc.CallOption) (*SimilarFeedbackResponse, error)
	SubmitFeedback(ctx context.Context, in *SubmitFeedbackRequest, opts ...grpc.CallOption) (*SubmitFeedbackResponse, error)
}

type feedbackServiceClient struct {
	cc *grpc.ClientConn
}

func NewFeedbackServiceClient(cc *grpc.ClientConn) FeedbackServiceClient {
	return &feedbackServiceClient{cc}
}

func (c *feedbackServiceClient) SimilarFeedback(ctx context.Context, in *SimilarFeedbackRequest, opts ...grpc.CallOption) (*SimilarFeedbackResponse, error) {
	out := new(SimilarFeedbackResponse)
	err := c.cc.Invoke(ctx, "/feedlightpb.FeedbackService/SimilarFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *feedbackServiceClient) SubmitFeedback(ctx context.Context, in *SubmitFeedbackRequest, opts ...grpc.CallOption) (*SubmitFeedbackResponse, error) {
	out := new(SubmitFeedbackResponse)
	err := c.cc.Invoke(ctx, "/feedlightpb.FeedbackService/SubmitFeedback", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FeedbackServiceServer is the server API for FeedbackService service.
type FeedbackServiceServer interface {
	SimilarFeedback(context.Context, *SimilarFeedbackRequest) (*SimilarFeedbackResponse, error)
	SubmitFeedback(context.Context, *SubmitFeedbackRequest) (*SubmitFeedbackResponse, error)
}

func RegisterFeedbackServiceServer(s *grpc.Server, srv FeedbackServiceServer) {
	s.RegisterService(&_FeedbackService_serviceDesc, srv)
}

func _FeedbackService_SimilarFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilarFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).SimilarFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedlightpb.FeedbackService/SimilarFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).SimilarFeedback(ctx, req.(*SimilarFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FeedbackService_SubmitFeedback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitFeedbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FeedbackServiceServer).SubmitFeedback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/feedlightpb.FeedbackService/SubmitFeedback",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FeedbackServiceServer).SubmitFeedback(ctx, req.(*SubmitFeedbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FeedbackService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "feedlightpb.FeedbackService",
	HandlerType: (*FeedbackServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimilarFeedback",
			Handler:    _FeedbackService_SimilarFeedback_Handler,
		},
		{
			MethodName: "SubmitFeedback",
			Handler:    _FeedbackService_SubmitFeedback_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "feedlightpb/feedlight.proto",
}

func (m *Feedback) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Feedback) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Feedback) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Feedback)))
		i += copy(dAtA[i:], m.Feedback)
	}
	if m.Score != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Score))
	}
	if m.Similar {
		dAtA[i] = 0x18
		i++
		if m.Similar {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Dissimilar {
		dAtA[i] = 0x20
		i++
		if m.Dissimilar {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if len(m.Response) > 0 {
		dAtA[i] = 0x2a
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Response)))
		i += copy(dAtA[i:], m.Response)
	}
	if m.SharePublicly {
		dAtA[i] = 0x30
		i++
		if m.SharePublicly {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.Created != 0 {
		dAtA[i] = 0x38
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Created))
	}
	if m.Id != 0 {
		dAtA[i] = 0x40
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func (m *SimilarFeedbackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimilarFeedbackRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintFeedlight(dAtA, i, uint64(m.Feedback.Size()))
	n1, err := m.Feedback.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	if len(m.Domain) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Domain)))
		i += copy(dAtA[i:], m.Domain)
	}
	return i, nil
}

func (m *SimilarFeedbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SimilarFeedbackResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Feedback) > 0 {
		for _, msg := range m.Feedback {
			dAtA[i] = 0xa
			i++
			i = encodeVarintFeedlight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	return i, nil
}

func (m *SubmitFeedbackRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitFeedbackRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Email) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Email)))
		i += copy(dAtA[i:], m.Email)
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintFeedlight(dAtA, i, uint64(m.Feedback.Size()))
	n2, err := m.Feedback.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	if len(m.Similar) > 0 {
		for _, msg := range m.Similar {
			dAtA[i] = 0x1a
			i++
			i = encodeVarintFeedlight(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if len(m.Domain) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(len(m.Domain)))
		i += copy(dAtA[i:], m.Domain)
	}
	return i, nil
}

func (m *SubmitFeedbackResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubmitFeedbackResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintFeedlight(dAtA, i, uint64(m.Id))
	}
	return i, nil
}

func encodeVarintFeedlight(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Feedback) Size() (n int) {
	var l int
	_ = l
	l = len(m.Feedback)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	if m.Score != 0 {
		n += 1 + sovFeedlight(uint64(m.Score))
	}
	if m.Similar {
		n += 2
	}
	if m.Dissimilar {
		n += 2
	}
	l = len(m.Response)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	if m.SharePublicly {
		n += 2
	}
	if m.Created != 0 {
		n += 1 + sovFeedlight(uint64(m.Created))
	}
	if m.Id != 0 {
		n += 1 + sovFeedlight(uint64(m.Id))
	}
	return n
}

func (m *SimilarFeedbackRequest) Size() (n int) {
	var l int
	_ = l
	l = m.Feedback.Size()
	n += 1 + l + sovFeedlight(uint64(l))
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	return n
}

func (m *SimilarFeedbackResponse) Size() (n int) {
	var l int
	_ = l
	if len(m.Feedback) > 0 {
		for _, e := range m.Feedback {
			l = e.Size()
			n += 1 + l + sovFeedlight(uint64(l))
		}
	}
	return n
}

func (m *SubmitFeedbackRequest) Size() (n int) {
	var l int
	_ = l
	l = len(m.Email)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	l = m.Feedback.Size()
	n += 1 + l + sovFeedlight(uint64(l))
	if len(m.Similar) > 0 {
		for _, e := range m.Similar {
			l = e.Size()
			n += 1 + l + sovFeedlight(uint64(l))
		}
	}
	l = len(m.Domain)
	if l > 0 {
		n += 1 + l + sovFeedlight(uint64(l))
	}
	return n
}

func (m *SubmitFeedbackResponse) Size() (n int) {
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovFeedlight(uint64(m.Id))
	}
	return n
}

func sovFeedlight(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozFeedlight(x uint64) (n int) {
	return sovFeedlight(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Feedback) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Feedback{`,
		`Feedback:` + fmt.Sprintf("%v", this.Feedback) + `,`,
		`Score:` + fmt.Sprintf("%v", this.Score) + `,`,
		`Similar:` + fmt.Sprintf("%v", this.Similar) + `,`,
		`Dissimilar:` + fmt.Sprintf("%v", this.Dissimilar) + `,`,
		`Response:` + fmt.Sprintf("%v", this.Response) + `,`,
		`SharePublicly:` + fmt.Sprintf("%v", this.SharePublicly) + `,`,
		`Created:` + fmt.Sprintf("%v", this.Created) + `,`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SimilarFeedbackRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SimilarFeedbackRequest{`,
		`Feedback:` + strings.Replace(strings.Replace(this.Feedback.String(), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`Domain:` + fmt.Sprintf("%v", this.Domain) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SimilarFeedbackResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SimilarFeedbackResponse{`,
		`Feedback:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Feedback), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SubmitFeedbackRequest) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SubmitFeedbackRequest{`,
		`Email:` + fmt.Sprintf("%v", this.Email) + `,`,
		`Feedback:` + strings.Replace(strings.Replace(this.Feedback.String(), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`Similar:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.Similar), "Feedback", "Feedback", 1), `&`, ``, 1) + `,`,
		`Domain:` + fmt.Sprintf("%v", this.Domain) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SubmitFeedbackResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SubmitFeedbackResponse{`,
		`Id:` + fmt.Sprintf("%v", this.Id) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringFeedlight(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Feedback) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Feedback: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Feedback: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feedback = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Score", wireType)
			}
			m.Score = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Score |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Similar", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Similar = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dissimilar", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Dissimilar = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Response", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Response = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SharePublicly", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SharePublicly = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Created", wireType)
			}
			m.Created = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Created |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimilarFeedbackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimilarFeedbackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimilarFeedbackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Feedback.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SimilarFeedbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SimilarFeedbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SimilarFeedbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Feedback = append(m.Feedback, Feedback{})
			if err := m.Feedback[len(m.Feedback)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitFeedbackRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitFeedbackRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitFeedbackRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Email", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Email = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Feedback", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Feedback.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Similar", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Similar = append(m.Similar, Feedback{})
			if err := m.Similar[len(m.Similar)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Domain", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFeedlight
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Domain = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubmitFeedbackResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubmitFeedbackResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubmitFeedbackResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipFeedlight(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthFeedlight
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFeedlight(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFeedlight
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFeedlight
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthFeedlight
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowFeedlight
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipFeedlight(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthFeedlight = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFeedlight   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("feedlightpb/feedlight.proto", fileDescriptor_feedlight_1b982d423c5632eb)
}

var fileDescriptor_feedlight_1b982d423c5632eb = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xbb, 0x6e, 0xd4, 0x40,
	0x14, 0xf5, 0xf5, 0x3e, 0xb2, 0x99, 0x88, 0x8d, 0x34, 0x4a, 0x16, 0xcb, 0xa0, 0x61, 0xe5, 0xf0,
	0xb0, 0x42, 0x58, 0x2b, 0x8b, 0x10, 0x52, 0xca, 0x14, 0xd4, 0xc8, 0xfb, 0x01, 0xc8, 0x8f, 0x59,
	0xef, 0x08, 0xdb, 0x63, 0xfc, 0x88, 0x44, 0x87, 0xa8, 0x29, 0x22, 0xf1, 0x13, 0xf4, 0x88, 0x7f,
	0x48, 0x19, 0x89, 0x86, 0x0a, 0xb1, 0x0e, 0x05, 0x65, 0x3e, 0x01, 0x65, 0x6c, 0x2f, 0xb6, 0x09,
	0x0b, 0x74, 0x73, 0xee, 0x9c, 0xd1, 0x39, 0xf7, 0x1c, 0x0d, 0xba, 0x35, 0xa7, 0xd4, 0xf5, 0x99,
	0xb7, 0x48, 0x23, 0xdb, 0x58, 0x9d, 0x27, 0x51, 0xcc, 0x53, 0x8e, 0xb7, 0x6a, 0x97, 0xea, 0x6d,
	0x8f, 0x73, 0xcf, 0xa7, 0x86, 0x15, 0x31, 0xc3, 0x0a, 0x43, 0x9e, 0x5a, 0x29, 0xe3, 0x61, 0x52,
	0x50, 0xd5, 0x47, 0x1e, 0x4b, 0x17, 0x99, 0x3d, 0x71, 0x78, 0x60, 0x78, 0xdc, 0xe3, 0x86, 0x18,
	0xdb, 0xd9, 0x5c, 0x20, 0x01, 0xc4, 0xa9, 0xa0, 0x6b, 0x17, 0x80, 0x06, 0xcf, 0x28, 0x75, 0x6d,
	0xcb, 0x79, 0x89, 0x55, 0x34, 0x98, 0x97, 0x67, 0x05, 0xc6, 0xa0, 0x6f, 0x9a, 0x2b, 0x8c, 0x77,
	0x50, 0x2f, 0x71, 0x78, 0x4c, 0x15, 0x79, 0x0c, 0x7a, 0xcf, 0x2c, 0x00, 0x56, 0xd0, 0x46, 0xc2,
	0x02, 0xe6, 0x5b, 0xb1, 0xd2, 0x19, 0x83, 0x3e, 0x30, 0x2b, 0x88, 0x09, 0x42, 0x2e, 0x4b, 0xaa,
	0xcb, 0xae, 0xb8, 0xac, 0x4d, 0xae, 0xb4, 0x62, 0x9a, 0x44, 0x3c, 0x4c, 0xa8, 0xd2, 0x2b, 0xb4,
	0x2a, 0x8c, 0xef, 0xa1, 0x61, 0xb2, 0xb0, 0x62, 0xfa, 0x22, 0xca, 0x6c, 0x9f, 0x39, 0xfe, 0x6b,
	0xa5, 0x2f, 0xde, 0xdf, 0x10, 0xd3, 0xe7, 0xe5, 0xf0, 0x4a, 0xdc, 0x89, 0xa9, 0x95, 0x52, 0x57,
	0xd9, 0x18, 0x83, 0xde, 0x31, 0x2b, 0x88, 0x87, 0x48, 0x66, 0xae, 0x32, 0x10, 0x43, 0x99, 0xb9,
	0x1a, 0x43, 0xa3, 0x59, 0xa1, 0x5b, 0xed, 0x6a, 0xd2, 0x57, 0x19, 0x4d, 0x52, 0xfc, 0xb4, 0xb5,
	0xf2, 0xd6, 0x74, 0x77, 0x52, 0x0b, 0x7b, 0x52, 0xf1, 0x8f, 0xbb, 0x67, 0x5f, 0xef, 0x48, 0xb5,
	0x3c, 0x46, 0xa8, 0xef, 0xf2, 0xc0, 0x62, 0xa1, 0x08, 0x64, 0xd3, 0x2c, 0x91, 0x66, 0xa2, 0x9b,
	0xbf, 0x49, 0x95, 0x6b, 0x35, 0xb5, 0x3a, 0xff, 0xac, 0xa5, 0x7d, 0x02, 0xb4, 0x3b, 0xcb, 0xec,
	0x80, 0xa5, 0x6d, 0xfb, 0x3b, 0xa8, 0x47, 0x03, 0x8b, 0xf9, 0x65, 0x5d, 0x05, 0x68, 0x08, 0xc9,
	0xff, 0xb3, 0xd4, 0x93, 0x7a, 0x9d, 0x7f, 0x35, 0xb8, 0xea, 0xfa, 0x57, 0x16, 0xdd, 0x46, 0x16,
	0x3a, 0x1a, 0xb5, 0x6d, 0x97, 0x51, 0x14, 0x05, 0x41, 0x55, 0xd0, 0xf4, 0xa3, 0x8c, 0xb6, 0x2b,
	0xd2, 0x8c, 0xc6, 0x27, 0xcc, 0xa1, 0xf8, 0x14, 0xd0, 0x76, 0x2b, 0x4a, 0xbc, 0xd7, 0xf0, 0x73,
	0x7d, 0xa7, 0xea, 0xdd, 0xf5, 0xa4, 0xc2, 0x82, 0x36, 0x7d, 0xfb, 0xf9, 0xfb, 0x7b, 0xf9, 0x40,
	0x7b, 0x20, 0x3e, 0xd2, 0xc9, 0xa1, 0xd1, 0xd2, 0x37, 0x5a, 0x0f, 0x8f, 0x60, 0x1f, 0xbf, 0x03,
	0x34, 0x6c, 0x6e, 0x84, 0xb5, 0xa6, 0xd8, 0x75, 0x2d, 0xa9, 0x7b, 0x6b, 0x39, 0xa5, 0x9f, 0x43,
	0xe1, 0xe7, 0xa1, 0x76, 0xff, 0x8f, 0x7e, 0x1a, 0xef, 0x8e, 0x60, 0xff, 0xf8, 0xe0, 0x7c, 0x49,
	0xa4, 0x2f, 0x4b, 0x22, 0x5d, 0x2e, 0x09, 0xbc, 0xc9, 0x09, 0x7c, 0xc8, 0x09, 0x9c, 0xe5, 0x04,
	0xce, 0x73, 0x02, 0xdf, 0x72, 0x02, 0x3f, 0x72, 0x22, 0x5d, 0xe6, 0x04, 0x4e, 0x2f, 0x88, 0x64,
	0xf7, 0xc5, 0x8f, 0x7f, 0xfc, 0x33, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x74, 0x16, 0xe2, 0x6a, 0x04,
	0x00, 0x00,
}
